import {$,esc} from './utils.js';
import {saveReleaseBanner,saveRelease,loadReleaseCounts} from './data.js';

export async function renderReleasesPage(state,onRefresh){
  $('#page').innerHTML=`<div class="card"><h2>Releases</h2><p class="muted">Choose which release you are building and manage Draft / Published / Archived status.</p><div id="releaseCounts">Loading…</div></div><div class="card"><div id="releaseCards"></div></div>`;
  const c=await loadReleaseCounts();
  const counts=new Map((c.data||[]).map(x=>[x.release_id,x]));
  $('#releaseCounts').innerHTML=c.error?`<div class="error">${esc(c.error.message)}</div>`:'<div class="small muted">Content counts are shown below.</div>';
  $('#releaseCards').innerHTML=(state.releases||[]).map(r=>{const n=counts.get(r.id)||{};return `<div class="item"><div class="item-main"><b>${esc(r.version)} — ${esc(r.title)}</b> <span class="pill">${esc(r.status||'draft')}</span><div class="small muted">${n.species_count||0} species • ${n.photo_count||0} photos • ${n.tip_count||0} ID cards • ${n.comparison_count||0} comparisons • ${n.distractor_count||0} distractors</div>${r.id===state.workingReleaseId?'<div class="ok" style="margin-top:6px">Current Working Release</div>':''}</div><button class="secondary editRelease" data-id="${r.id}">Manage</button></div>`}).join('');
  document.querySelectorAll('.editRelease').forEach(b=>b.onclick=()=>openReleaseModal(state,state.releases.find(r=>r.id===b.dataset.id),onRefresh));
}
function openReleaseModal(state,r,onRefresh){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-card"><h2>${esc(r.version)} — ${esc(r.title)}</h2><div id="relMsg"></div><label>Status</label><select id="relStatus" class="field"><option value="draft" ${r.status==='draft'?'selected':''}>Draft</option><option value="published" ${r.status==='published'?'selected':''}>Published</option><option value="archived" ${r.status==='archived'?'selected':''}>Archived</option></select><label>Launch date/time (optional)</label><input id="relLaunch" class="field" type="datetime-local" value="${r.launch_at?new Date(r.launch_at).toISOString().slice(0,16):''}"><div class="row" style="margin-top:16px"><button id="relSave" class="primary">Save Release</button><button id="relWork" class="secondary">Make Working Release</button><button id="relCancel" class="secondary">Cancel</button></div></div>`;document.body.appendChild(m);$('#relCancel',m).onclick=()=>m.remove();$('#relWork',m).onclick=()=>{state.workingReleaseId=r.id;localStorage.setItem('fid_working_release',r.id);m.remove();onRefresh();};$('#relSave',m).onclick=async()=>{const status=$('#relStatus',m).value;const payload={status,launch_at:$('#relLaunch',m).value?new Date($('#relLaunch',m).value).toISOString():null};if(status==='published'&&!r.published_at)payload.published_at=new Date().toISOString();const x=await saveRelease(r.id,payload);if(x.error){$('#relMsg',m).innerHTML=`<div class="error">${esc(x.error.message)}</div>`;return}m.remove();await onRefresh();};}

export function renderReleaseBannerPage(state,onRefresh){const releases=[...(state.releases||[])];const selected=releases.find(r=>r.id===state.workingReleaseId)||releases[0];if(!selected){$('#page').innerHTML='<div class="card"><h2>Release Banner</h2><div class="muted">No release records found.</div></div>';return;}$('#page').innerHTML=`<div class="card"><h2>Release Banner</h2><p class="muted">Editing banner for the current Working Release.</p><div class="ok"><b>${esc(selected.version)} — ${esc(selected.title)}</b> (${esc(selected.status)})</div></div><div class="card" id="releaseEditor"></div>`;paintEditor(selected,onRefresh);}
function paintEditor(release,onRefresh){const box=$('#releaseEditor');box.innerHTML=`<h3>${esc(release.version)} Banner</h3><div id="releaseMsg"></div><label class="check"><input id="bannerEnabled" type="checkbox" ${release.banner_enabled?'checked':''}> Show banner in game</label><label>Banner title</label><input id="bannerTitle" class="field" value="${esc(release.banner_title||'')}"><label>Banner body</label><textarea id="bannerBody" class="field">${esc(release.banner_body||'')}</textarea><label>Banner stats / footer line</label><input id="bannerMeta" class="field" value="${esc(release.banner_meta||'')}"><div style="margin-top:16px"><div class="small muted" style="margin-bottom:6px">Preview</div><div class="update-banner"><div id="prevTitle" class="update-banner-title">${esc(release.banner_title||'')}</div><div id="prevBody" class="update-banner-copy">${esc(release.banner_body||'')}</div><div id="prevMeta" class="update-banner-meta">${esc(release.banner_meta||'')}</div></div></div><button id="saveBanner" class="primary" style="margin-top:16px">Save Banner</button>`;const sync=()=>{$('#prevTitle').textContent=$('#bannerTitle').value;$('#prevBody').textContent=$('#bannerBody').value;$('#prevMeta').textContent=$('#bannerMeta').value};$('#bannerTitle').oninput=sync;$('#bannerBody').oninput=sync;$('#bannerMeta').oninput=sync;$('#saveBanner').onclick=async()=>{const payload={banner_enabled:$('#bannerEnabled').checked,banner_title:$('#bannerTitle').value.trim()||null,banner_body:$('#bannerBody').value.trim()||null,banner_meta:$('#bannerMeta').value.trim()||null};const x=await saveReleaseBanner(release.id,payload);if(x.error){$('#releaseMsg').innerHTML=`<div class="error">${esc(x.error.message)}</div>`;return}$('#releaseMsg').innerHTML='<div class="ok">Banner saved.</div>';await onRefresh();};}
